# Generated by Django 5.0.7 on 2024-12-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
